on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      - devel
    paths:
      - DESCRIPTION
      - .github/workflows/main.yml

name: Build site
jobs:
  render:
    name: Build site
    runs-on: macOS-latest
    steps:
      - name: Install pkgdown
        run: Rscript -e 'install.packages("pkgdown")'
      - name: Build site
        run: Rscript -e 'pkgdown::build_site()'
      - name: Commit results
        run: |
          git commit codemeta.json -m 'Re-build site with pkgdown' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
